function [ag_data_path, climate_data_path, ghg_data_path] = fcn_create_path(parameters)
    ag_data_path = strcat(parameters.agriculture_data_folder, 'NEV_ag_',...
        parameters.clim_scen_string, '_', parameters.temp_pct_string, '_',...
        parameters.rain_pct_string, '_data.mat');

    climate_data_path = strcat(parameters.climate_data_folder, 'NEV_climate_',...
        parameters.clim_scen_string, '_', parameters.temp_pct_string, '_',...
        parameters.rain_pct_string, '_data.mat');

    ghg_data_path = strcat(parameters.agricultureghg_data_folder, 'NEV_ghg_',...
       parameters.clim_scen_string, '_', parameters.temp_pct_string, '_',...
       parameters.rain_pct_string, '_data.mat');
end

