function [subctch_em_summary, subctch_em_out] = fcn_transfer_model_firstorder(water_transfer_data_folder, ...
                                                                              subctch_info, ...
                                                                              decade_str, ...
                                                                              models_lu)

    subctch_em_lu = fcn_transfer_model_fromland(water_transfer_data_folder, ...
                                                subctch_info, ...
                                                decade_str, ...
                                                models_lu);
    subctch_em_in = subctch_em_lu;
    
    subctch_em_out = fcn_transfer_model_instream(subctch_em_in);
    
    subctch_em_summary = fcn_subctch_summary_calc(subctch_em_out, ...
                                                  decade_str);
       
end