% ImportBiodiversityJNCC
% ======================
% Author: Nathan Owen
% Last modified: 18/09/2019
% Import all data required for running the JNCC biodiversity models. Store
% in Biodiversity structure in a .mat file, to be loaded from within 
% fcn_run_biodiversity_jncc.m

function Biodiversity = ImportBiodiversityJNCC(conn, parameters)

    %% (1) Load, prepare and save data
    %  ===============================
    tic

    % (a) Coefficients for the 100 species distribution models
    % --------------------------------------------------------
    filename    = 'beta_JNCC100_interact_quad.csv';
    sheetIn     = 1;
    rangeIn     = 'B2:CW772';
    
    [Data, ~, ~] = xlsread(strcat(parameters.biodiversity_data_folder_jncc, filename), sheetIn, rangeIn); 
    Biodiversity.Coefficients = Data;
    
    % (b) Grid cell data needed for the 100 models
    % --------------------------------------------
    sqlquery = ['SELECT ', ...
                    'new2kid, ', ...
                    'const, ', ...
                    'coast_ha, ', ...
                    'fwater_ha, ', ...
                    'marine_ha, ', ...
                    'avElev_cell, ', ...
                    'aspect, ', ...
                    'pca_clay, ', ...
                    'pca_urb_lake, ', ...
                    'pca_l_sand, ', ...
                    'pca_loam, ', ...
                    'pca_s_loam, ', ...
                    'pca_clay_loam, ', ...
                    'pca_sand, ', ...
                    'pca_silt_loam, ', ...
                    'pca_ph1, ', ...
                    'pca_ph2, ', ...
                    'pca_ph3, ', ...
                    'pca_ph4, ', ...
                    'pca_sw1, ', ...
                    'pca_sw2, ', ...
                    'pca_sw3, ', ...
                    'pca_sw4, ', ...
                    'p_maize, ' ...
                    'p_othcer, ' ...
                    'p_hort, ' ...
                    'p_othcrps, ' ...
                    'p_othfrm ' ...
                'FROM nevo.nevo_variables ORDER BY new2kid'];
    setdbprefs('DataReturnFormat','table');
    dataReturn  = fetch(exec(conn,sqlquery));
    data_cells = dataReturn.Data;
    
    % Save 2km grid cell new2kid separately
    Biodiversity.new2kid = data_cells.new2kid;
    
    % Rest goes into Biodiversity.Data_cells table
    Biodiversity.Data_cells = data_cells(:, 2:end);
    
    % (c) Grid cell climate data needed for the 100 models
    % ----------------------------------------------------
    % Current climate
    % Note: this was prepared by Emma Wright (JNCC)
    filename = 'JNCC_data_input.csv';
    climate_cells_now = readtable(strcat(parameters.biodiversity_data_folder_jncc, filename), 'TreatAsEmpty', 'NA');
    climate_cells_now = climate_cells_now(:, {'new2kid', 'TP_AS_6190', 'bio3', 'bio7', 'bio8', 'bio9', 'bio10', 'bio11'});
    climate_cells_now.Properties.VariableNames{'TP_AS_6190'} = 'rain';
    
%     % Check new2kid cells match
%     isequal(climate_cells_now.new2kid, Biodiversity.new2kid)
    
    % Save to Biodiversity structure
    Biodiversity.Climate_cells_now = climate_cells_now;
    
    % Future climate for NEVO
    % Note: this was prepared by Greg Smith (LEEP)
    sqlquery = ['SELECT ', ...
                    'new2kid, ', ...
                    'rain_20, rain_30, rain_40, rain_50, ', ...
                    'bio3_20, bio3_30, bio3_40, bio3_50, ' ...
                    'bio7_20, bio7_30, bio7_40, bio7_50, ' ...
                    'bio8_20, bio8_30, bio8_40, bio8_50, ' ...
                    'bio9_20, bio9_30, bio9_40, bio9_50, ' ...
                    'bio10_20, bio10_30, bio10_40, bio10_50, ' ...
                    'bio11_20, bio11_30, bio11_40, bio11_50 ' ...
                'FROM nevo."JNCC_climate_avg" ORDER BY new2kid'];
    setdbprefs('DataReturnFormat','table');
    dataReturn  = fetch(exec(conn,sqlquery));
    climate_cells_future = dataReturn.Data;
    
%     % Check new2kid cells match
%     isequal(climate_cells_future.new2kid, Biodiversity.new2kid)
    
    % Save to Biodiversity structure
    Biodiversity.Climate_cells_future = climate_cells_future;    
    toc
end