function benefit_pollination_ann = fcn_calc_benefit_pollination(start_year, scheme_length, discount_constants, es_pollination)
    % Calculate the year in the 4 decades which relates to the end of the
    % current scheme, if the scheme ends after the fourth decade set to 40
    % and add extra annuity
    end_year = min(40, start_year + (scheme_length - 1));
    
    if (end_year < 40)
        % Return annuities in each decade as matrix
        % !!! this is hard coded to be a 5 year scheme !!!
        benefit_pollination_ann = [repmat(es_pollination.pollinator_val_20, 1, 5) * discount_constants.delta_scheme_length * discount_constants.gamma_10, ...
                                   zeros(size(es_pollination.pollinator_val_30)), ...
                                   zeros(size(es_pollination.pollinator_val_40)), ...
                                   zeros(size(es_pollination.pollinator_val_50))];
    else
        % Same as above, but use 2050's annuity for additional years
        benefit_pollination_ann = [es_pollination.pollinator_val_20, ...
                                   es_pollination.pollinator_val_30, ...
                                   es_pollination.pollinator_val_40, ...
                                   es_pollination.pollinator_val_50, ...
                                   es_pollination.pollinator_val_50];
    end
end