function [benefit_totn_ann, benefit_totp_ann] = fcn_calc_benefit_water_quality(start_year, scheme_length, discount_constants, water_quality_table)

    % Calculate the year in the 4 decades which relates to the end of the
    % current scheme, if the scheme ends after the fourth decade set to 40
    % and add extra annuity
    end_year = min(40, start_year + (scheme_length - 1));
    
    if (end_year < 40)
        % Return annuities in each decade as matrix
        % !!! this is hard coded to be a 5 year scheme !!!
        benefit_totn_ann = [repmat(water_quality_table.totn_ann_20, 1, 5) * discount_constants.delta_scheme_length * discount_constants.gamma_10, ...
                            zeros(size(water_quality_table.totn_ann_30)), ...
                            zeros(size(water_quality_table.totn_ann_40)), ...
                            zeros(size(water_quality_table.totn_ann_50))];
        benefit_totp_ann = [repmat(water_quality_table.totp_ann_20, 1, 5) * discount_constants.delta_scheme_length * discount_constants.gamma_10, ...
                            zeros(size(water_quality_table.totp_ann_30)), ...
                            zeros(size(water_quality_table.totp_ann_40)), ...
                            zeros(size(water_quality_table.totp_ann_50))];
    else
        % Same as above, but use 2050's annuity for additional years
        benefit_totn_ann = [water_quality_table.totn_ann_20, ...
                            water_quality_table.totn_ann_30, ...
                            water_quality_table.totn_ann_40, ...
                            water_quality_table.totn_ann_50, ...
                            water_quality_table.totn_ann_50];
        benefit_totp_ann = [water_quality_table.totp_ann_20, ...
                            water_quality_table.totp_ann_30, ...
                            water_quality_table.totp_ann_40, ...
                            water_quality_table.totp_ann_50, ...
                            water_quality_table.totp_ann_50];
    end

end