function benefit_non_use_pollination_ann = fcn_calc_benefit_non_use_pollination(start_year, scheme_length, discount_constants, es_non_use_pollination)
    % Calculate the year in the 4 decades which relates to the end of the
    % current scheme, if the scheme ends after the fourth decade set to 40
    % and add extra annuity
    end_year = min(40, start_year + (scheme_length - 1));
    
    if (end_year < 40)
        % Return annuities in each decade as matrix
        % !!! this is hard coded to be a 5 year scheme !!!
        benefit_non_use_pollination_ann = [repmat(es_non_use_pollination.wtp_change_20, 1, 5) * discount_constants.delta_scheme_length * discount_constants.gamma_10, ...
                                           zeros(size(es_non_use_pollination.wtp_change_30)), ...
                                           zeros(size(es_non_use_pollination.wtp_change_30)), ...
                                           zeros(size(es_non_use_pollination.wtp_change_30))];
    else
        % Same as above, but use 2050's annuity for additional years
        benefit_non_use_pollination_ann = [es_non_use_pollination.wtp_change_20, ...
                                           es_non_use_pollination.wtp_change_30, ...
                                           es_non_use_pollination.wtp_change_40, ...
                                           es_non_use_pollination.wtp_change_50, ...
                                           es_non_use_pollination.wtp_change_50];
    end
end